# Generated by Django 4.1.7 on 2023-03-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.place')),
            ],
        ),
    ]
