# Generated by Django 4.1.7 on 2023-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
