# Generated by Django 4.1.7 on 2023-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_messages_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
